films/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

app_name = 'films'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<review_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<title>[\w\-]+)/$',views.title, name='title')
    # ex: /polls/5/results/
]

themovieroom/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from .admin import *

urlpatterns = [
    url(r'^admin_site/', admin_site.urls, name='admin'),
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.SearchListView, name='SearchListView'),
    url(r'^person/(?P<person_id>[0-9]+)/$', views.persons, name='persons'),
    url(r'^reviews/', include('films.urls')),
    url(r'^features/', views.features_view, name='features'),
    url(r'^features/(?P<feature_id>[0-9]+)/$', views.feature_view, name='feature'),
    url(r'^tinymce/', include('tinymce.urls')),

]
handler404 = 'themovieroom.views.page_not_found'
handler500 = 'themovieroom.views.page_not_found'


from django.conf import settings

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from datetime import date
from math import floor, ceil
import ast

STATUS_CHOICES = (
    ('d', 'Draft'),
    ('p', 'Published'),
    ('w', 'Withdrawn'),
)


# Create your models here.
class person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField(default='1990-01-01')
    date_of_death = models.DateField(blank=True, null=True)

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    imdb = models.CharField(max_length = 7, default='')
    image = models.ImageField(blank=True, upload_to = 'images')
    tmdb = models.IntegerField(default = 0, blank = True)
    def age(self):
        today = date.today()
        if self.date_of_death:
            today = self.date_of_death
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
    def name(self):              # __unicode__ on Python 2
        return "%s %s" % (self.first_name, self.last_name)
    def reviewed_films(self):
        films = []
        for f in self.cast.all():
            if f.review and f.review.status=='p':
                films += [ f ]
        for f in self.director.all():
            if f.review and f.review not in self.cast.all() and f.review.status=='p':
                films += [ f ]
        
        return films

    def __str__(self):              # __unicode__ on Python 2
        return "%s %s" % (self.first_name, self.last_name)

class film(models.Model):
    title = models.CharField(max_length=200)
    release_date = models.DateField('Release Date', null = True)
    runtime = models.IntegerField(default = 0)
    director = models.ManyToManyField(person, related_name='director')
    cast = models.ManyToManyField(person, related_name='cast')
    imdb = models.CharField(max_length = 7, default='')
    tmdb = models.IntegerField(default = 0)
    def __str__(self):
        return self.title

class review(film):
    body = models.CharField(max_length= 10000)
    synopsis = models.CharField(max_length = 1000, null=True, blank = True, default = '')
    quote = models.CharField(max_length = 500, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null = True)
    link_title = models.CharField(max_length = 40, default = '')
    RATING_CHOICES = (
        (0, 0),
        (1, 0.5),
        (2, 1),
        (3, 1.5),
        (4, 2),
        (5, 2.5),
        (6, 3.0),
        (7, 3.5),
        (8, 4.0),
        (9, 4.5),
        (10, 5.0),
    )
    rating = models.IntegerField(choices = RATING_CHOICES)
    image = models.ImageField(blank=True, upload_to = 'images')
    image_small = models.ImageField(blank=True, upload_to = 'images')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')

    def __str__(self):
        return self.title
    def short_title(self):
        short = self.title.lower.replace(' ','_')
        return short

    def stars(self):
        starred = []
        if (self.rating <= 10):
            rating = self.rating / 2.0
            for i in range(int(floor(rating))):
                starred += [ 1 ]
            if rating%1 == 0.5:
                starred += [ 0.5]
            for i in range(int(5 - ceil(rating))):
                starred += [ 0 ]
        return starred
    def print_review(self):
        return self.body

class feature(models.Model):
    title = models.CharField(max_length = 200, default = "Feature")
    text = models.CharField(max_length = 10000)
    synopsis = models.CharField(max_length = 1000, default = '')
    image = models.ImageField(blank=True, upload_to = 'images')
    image_small = models.ImageField(blank=True, upload_to = 'images')
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')
    published_date = models.DateTimeField(auto_now=True, null = True)


    def name(self):              # __unicode__ on Python 2
        return "%s" % (self.title)
    def __str__(self):              # __unicode__ on Python 2
        return "%s" % (self.title)

films/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import review, film

def index(request):
    return render(request, 'reviews.html', {'reviews' : review.objects.filter(status='p').order_by('-published_date')})

def detail(request, review_id):
    r = get_object_or_404(review, id=review_id,status='p')
    return render(request, 'review.html', {'review': r})

def title(request, title):
    r = get_object_or_404(review, link_title = title, status='p')
    return render(request, 'review.html', {'review': r})

def preview(request, review_id):
    r = get_object_or_404(review, id=review_id,status='d')
    return render(request, 'review.html', {'review': r})

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load common %}
{% load user_agents %}


<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oswald" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oswald:300" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Merriweather" />
{% block title %}
<title>The Movie Room</title>
<meta name="description" content="Reviews of movies new and old"/>
<meta property="og:title" content="The Movie Room" />
<meta property="og:url" content="https://www.themovieroom.co.uk/" />
<meta property="og:description" content="Reviews of movies new and old">
<meta property="og:image" content="{% static 'images/favicon.ico' %}" />
{% endblock %}
<meta property="og:type" content="article" />
<meta property="og:locale" content="en_GB" />
<meta charset="iso-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'styles/layout.css' %}" type="text/css"/>
{% if request|is_mobile %}
<link rel="stylesheet" href="{% static 'styles/mobile.css' %}" type="text/css"/>
{% endif %}

<!--[if lt IE 9]><script src="scripts/html5shiv.js"></script><![endif]-->
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/themovieroom_152x152.png' %}"/>
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/themovieroom_180x180.png' %}"/>
<link rel="apple-touch-icon" sizes="167x167" href="{% static 'images/themovieroom_167x167.png' %}"/>

</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
         <img src="{% static 'images/themovieroom2.png' %}" alt="">
    </div>
    <nav>
      <ul>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'films:index' %}">Reviews</a></li>
        <li><a href="{% url 'features' %}">Features</a></li>
      </ul>
      </nav>
    <form action="{% url 'SearchListView' %}" method="get">
      <fieldset>
        <legend>Search:</legend>
        <input type="text" placeholder="Search themovieroom.co.uk..&hellip;" name="search", onFocus="this.value=(this.value=='Search TheMovieRoom.co.uk&hellip;')? '' : this.value ;">
        <input type="submit" id="sf_submit" value="">
      </fieldset>
    </form>
  </header>
</div>
<!-- content -->
<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- Slider -->
    <section id="slider" class="clear">
      {% block image %}
      {% endblock %}
    </section>
    <!-- Content -->
    <div id="homepage">
      <!-- ########################################################################################## -->
      <section class="clear">
        <article class="{% if request|is_mobile %}three_third{% else %}two_third{% endif %}">
	  {% block body %}
	  {% endblock %}
        </article>
	{% if not request|is_mobile %}
        <article class="one_third lastbox">
	  {% block sidebar %}
	  {% endblock %}
        </article>
	{% endif %}
      </section>
    </div>
    <!-- / content body -->
  </div>
</div>
<!-- Footer -->
<div class="wrapper row3">
  <footer id="footer" class="clear">
    <p class="fl_left">Copyright &copy; 2019 - All Rights Reserved - <a href="#">TheMovieRoom.co.uk</a></p>
    <p class="fl_right">This website uses the TMDb API but is not endorsed or certified by TMDb.</a></p>
  </footer>
</div>
</body>
</html>

templates/base_index.html
{% extends "base.html" %}')
{% load static %}
{% load common %}
        
{% block title %}<title> The Movie Room </title>{% endblock %}


{% block sidebar %}
<table id = "cinema"><tbody>
    <tr><th><img height=18px src = {% static 'images/incinema.png' %}>&nbsp;&nbsp;In Cinemas Now</th></tr>
    <tr><td> {% block cinema1 %}{% endblock %}</td></tr>
    <tr><td> {% block cinema2 %}{% endblock %}</td></tr>
    <tr><td> {% block cinema3 %}{% endblock %}</td></tr>
    <tr><td> {% block cinema4 %}{% endblock %}</td></tr>
    <tr><td> {% block cinema5 %}{% endblock %}</td></tr>
    <tr><td> {% block cinema6 %}{% endblock %}</td></tr>
    <tr><td> {% block cinema7 %}{% endblock %}</td></tr>
    <tr><td> {% block cinema8 %}{% endblock %}</td></tr>
    

    <tr><th><img height=18px src = {% static 'images/comingsoon.png' %}>&nbsp;&nbsp;Coming Soon</th></tr>
    <tr><td> {% block coming1 %}{% endblock %}</td></tr>
    <tr><td> {% block coming2 %}{% endblock %}</td></tr>
    <tr><td> {% block coming3 %}{% endblock %}</td></tr>
    <tr><td> {% block coming4 %}{% endblock %}</td></tr>
    <tr><td> {% block coming5 %}{% endblock %}</td></tr>
    <tr><td> {% block coming6 %}{% endblock %}</td></tr>
    <tr><td> {% block coming7 %}{% endblock %}</td></tr>
    <tr><td> {% block coming8 %}{% endblock %}</td></tr>
</tbody></table>
{% endblock %}
{% block image %}
{% endblock %}
{% block body %}

{% for review in reviews %}
{% if review.id == mainid %}

<div class = "mainsynopsis"><a href="{% url 'films:title' review.link_title %}">
<figure><img src = "{{ review.image_small.url }}"><br>
  <figcaption id = "title"> <h1> {{review.title}} ({{review.release_date.year}}) </h1>
        {% for star in review.stars  %}
        {% if star == 1 %} <span class="star-icon full">&#9734;</span>
        {% elif star == 0.5 %} <span class="star-icon half">&#9734;</span>
        {% elif star == 0 %} <span class="star-icon">&#9734;</span>
        {% endif %}
        {% endfor %}
      </figcaption>
      <figcaption id = "synopsis">
        {{review.synopsis}}
      </figcaption>
  </figure></a>
</div>
{% endif %}
{% endfor %}
<div class = "synopsis">
  {% for review in reviews %}
  {% if review.id != mainid  %}
  <a href = "{% url 'films:title' review.link_title %}">
    <figure>
      <img src = "{{review.image_small.url}}">
      <figcaption>
        {{review.title}} ({{review.release_date.year}})<br>
	<div id = "stars">
        {% for star in review.stars  %}
        {% if star == 1 %} <span class="star-icon full">&#9734;</span>
        {% elif star == 0.5 %} <span class="star-icon half">&#9734;</span>
        {% elif star == 0 %} <span class="star-icon">&#9734;</span>
        {% endif %}
        {% endfor %}
	</div>
      </figcaption>
    </figure>
  </a>
  {% endif %}
  {% endfor %}
  
</div>
<!-- <footer class="more"><a href="#">Read More &raquo;</a></footer> -->

<div class = "features">
  {% for feature in features %}
  <div class = "feature">
    <h1>{{feature.title}}</h1>
    {{feature.text}}
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/create_home_page.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
</div>
{% endblock %}



{% block content %}
{% if form %}
<div id="content-main">
    <form action="{% url 'admin:update' %}" method="POST">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>
</div>
{% else %}
Made new home page
{% endif %}
{% endblock %}

templates/features.html
{% extends "base.html" %}
{% load static %}


{% block title %}
<title>Features</title>
<meta name="description" content="Reviews of movies new and old"/>
<meta property="og:title" content="Features | The Movie Room" />
<meta property="og:url" content="https://themovieroom.co.uk/" />
<meta property="og:description" content="Latest features on themovieroom.co.uk" />
<meta property="og:image" content="{% if features.count > 0 %}{{ features.0.image.url }} {% else %} {% static 'images/favicon.ico' %} {% endif %}" /> 
{% endblock %}




{% block image %}
{% endblock %}

{% block body %}
{% if features.count > 0 %}
<table id="t02">
<tr><th><h2>Latest Features</h2></th></tr>
{% for feature in features %}
  <tr><td> <a href = "{% url 'films:features' film.id %}">{{feature.title}}</a></td></tr>
  {% endfor %}
</table>
{% else %}
<h1> Features coming soon! </h1>
{% endif %}

<!-- <footer class="more"><a href="#">Read More &raquo;</a></footer> -->
{% endblock %}

templates/film.html
{% extends "base.html" %}
{% load static %}


{% block title %}{{ review.title }}{% endblock %}


{% block image %}
<article class = "review">
<figure><img src="/{{review.image }}" alt=""></figure>
</article>
  <article class = "quote" >
"{{review.quote}}"</article>

{% endblock %}


{% block body %}
<h2>{{ review.title }} ( {{ review.release_date.year }} )</h2>
<ul>
  <!---<li> Director:
    {% for person in review.director.all %}
    {{ person.first_name }} {{person.last_name}}
    {% endfor %}
  <li>Runtime: {{ review.runtime }} minutes</li>
  <li>Starring
    {% for person in review.cast.all %}
    {% if forloop.first %}{% else %}
    {% if forloop.last %} and {% else %}, {% endif %}
    {% endif %}{{ person.first_name }} {{person.last_name}}
    {% endfor %}
  </li>-->
  <li>
    {% for star in review.stars  %}
    {% if star == 1 %} ★
    {% elif star == 0.5 %} 1/2
    {% endif %}
    {% endfor %}
    </li>
</ul>
<div class = "review">{{review.body}}</div>
{% endblock %}


{% block sidebar %}

<table id = "t01"><tbody>
<tr><th>Directed by</th></tr>
    {% for person in review.director.all %}
<tr><td> <a href = "{% url 'persons' person.id %}">{{ person.first_name }} {{person.last_name}}</td></tr>
    {% endfor %}
<tr><th>Starring</th></tr>
    {% for person in review.cast.all %}    
    <tr><td> <a href = "{% url 'persons' person.id %}">{{ person.first_name }} {{person.last_name}}</td></tr>
    {% endfor %}

<tr><th>Runtime: {{ review.runtime }} minutes</th></tr>
  <tr><td>
<span class="imdbRatingPlugin" data-user="ur4256421" data-title="tt{{ review.imdb }}" data-style="p4"><a href="http://www.imdb.com/title/tt{{ review.imdb }}/?ref_=plg_rt_1"><img src="http://g-ecx.images-amazon.com/images/G/01/imdb/plugins/rating/images/imdb_31x14.png" alt="{{review.title}} ({{review.release_date.year}}) on IMDb" />
</a></span><script>(function(d,s,id){var js,stags=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}js=d.createElement(s);js.id=id;js.src="http://g-ec2.images-amazon.com/images/G/01/imdb/plugins/rating/js/rating.min.js";stags.parentNode.insertBefore(js,stags);})(document,'script','imdb-rating-api');</script>
</th></td>
</tbody></table>
{% endblock %}

templates/films.html
{% extends "base.html" %}
{% load static %}


{% block title %}My amazing blog{% endblock %}



{% block image %}
{% endblock %}

{% block body %}
<ul>{% if films.count > 0 %}
<h2>Reviews</h2>
  {% for film in films %}
  <li> <a href = "{% url 'films:detail' film.id %}">{{film.title}} ({{film.release_date.year}})</a></li>
  {% endfor %}
</ul>
{% endif %}
<ul>{% if persons.count > 0 %}
<h2>People</h2>
  {% for person in persons %}
  <li> <a href = "{% url 'persons' person.id %}"> {{person.first_name}} {{person.last_name}}</a></li>
{%if person.cast.count > 0 %}
<ul>
{% for film in person.cast.all %}
  <li> <a href = "{% url 'films:detail' film.id %}">{{film.title}} ({{film.release_date.year}})</a></li>
  {% endfor %}
  </ul>
{% endif %}
{%if person.director.count > 0 %}
Directed
{% for film in person.director.all %}
{{film.title}}<br>
{% endfor %}
{% endif %}
  {% endfor %}
</ul>
{% endif %}
<footer class="more"><a href="#">Read More &raquo;</a></footer>
{% endblock %}

templates/person.html
{% extends "base.html" %}
{% load static %}


{% block title %}
<title>{{ person.name }} | The Movie Room </title>
<meta name="description" content="Reviews of movies new and old"/>
<meta property="og:title" content="{{ review.title }} ({{ review.release_date.year }}) | The Movie Room" />
<meta property="og:url" content="https://www.themovieroom.co.uk/" />
<meta property="og:description" content="{{ person.name }} at The Movie Room">
<meta property="og:image" content="{%if person.image %}{{ person.image.url }} {%else %}{% static 'images/favicon.ico' %} {% endif %}" />
{% endblock %}

{% block body %}
{% if person.image %}
<img id = "profile" src="{{ person.image.url }}" alt="">
{% endif %}
<h2>{{ person.first_name }} {{ person.last_name }}</h2>
<br>
{% if person.date_of_death %}
Date of Birth : {{person.date_of_birth}}<br>
Died : {{person.date_of_death}} ( Age {{ person.age }} )<br>
{% else %}
DOB: {{person.date_of_birth}} ( Age {{ person.age }} )<br>
{% endif %}
{%if person.cast.count > 0 or  person.director.count > 0 %}
Reviewed Filmography:<br>
{% for film in person.reviewed_films %}
   <a href = "{% url 'films:detail' film.id %}">{{film.title}} ({{film.release_date.year}})</a><br>
  {% endfor %}
{% endif %}
</ul>
{% endblock %}

templates/results.html
{% extends "base.html" %}
{% load static %}


{% block title %}
<title>Search Results for {{ query }} | The Movie Room </title>
<meta name="description" content="Reviews of movies new and old"/>
<meta property="og:title" content="Search results for {{query}} | The Movie Room" />
<meta property="og:url" content="https://themovieroom.co.uk/" />
<meta property="og:description" content="" />
<meta property="og:image" content="{% static 'images/favicon.ico' %}" />



{% endblock %}



{% block image %}
{% endblock %}

{% block body %}
{% if persons.count == 0 and reviews.count == 0 %}
Sorry, no search results found for "{{ query }}"
{% else %}
Search results for "{{ query }}"
{% endif %}
{% if reviews.count > 0 %}
<table id="t02">
<tr><th>
{% if reviews.count == 1%}
Found 1 Review
{% else %}
Found {{ reviews.count }} Reviews
{% endif %}
</th></tr>
{% for film in reviews %}
  <tr><td> <a href = "{% url 'films:title' film.link_title %}">{{film.title}} ({{film.release_date.year}})</a></td></tr>
  {% endfor %}
</table>
{% endif %}
{% if persons.count > 0 %}
<table id = "t02">
<tr><th>
{% if persons.count == 1 %}
Found 1 Person
{% else %}
Found {{persons.count}} People
{% endif %}
</tr></th>
  {% for person in persons %}
  <tr><td> <a href = "{% url 'persons' person.id %}"> {{person.first_name}} {{person.last_name}}</a></td></tr>
</table>

<!--{%if person.cast.count > 0 %}
{% for film in person.cast.all %}
  <li> <a href = "{% url 'films:detail' film.id %}">{{film.title}} ({{film.release_date.year}})</a></li>
  {% endfor %}
-->
  </ul>
{% endif %}
{%if person.director.count > 0 %}
Directed
{% for film in person.director.all %}
{{film.title}}<br>
{% endfor %}
{% endif %}
  {% endfor %}
</ul>
{% endif %}
<!-- <footer class="more"><a href="#">Read More &raquo;</a></footer> -->
{% endblock %}

templates/review.html
{% extends "base.html" %}
{% load static %}
{% load user_agents %}

{% block title %}
<title>{{ review.title }} ({{ review.release_date.year }}) | The Movie Room </title>
<meta name="description" content="Reviews of movies new and old"/>
<meta property="og:title" content="{{ review.title }} ({{ review.release_date.year }}) | The Movie Room" />
<meta property="og:url" content="https://www.themovieroom.co.uk/" />
<meta property="og:description" content="{% for star in review.stars  %}{% if star == 1 %} ★  {% elif star == 0.5 %} 1/2 {% endif %} {% endfor %}">
{% if review.image_small %}
<meta property="og:image" content="{{ review.image_small.url }}" />
{% endif %}

{% endblock %}

{% block image %}
<article class = "review">
{% if review.image %}
<figure><img src="{{ review.image.url }}" alt=""></figure>
{% endif %}
</article>
{% if review.quote %}
{% if request|is_mobile %}
<blockquote id="mobilequote">
  {{review.quote}}
  </blockquote>
{% else %}
<blockquote>
{{review.quote}}
</blockquote>
{% endif %}
{% endif %}

{% endblock %}

  {% block body %}

<article class = "review">
<h2>{{ review.title }} ( {{ review.release_date.year }} )</h2>
<h3><span id = "stars">{% for star in review.stars  %}{% if star == 1 %}<span class="star-icon full">&#9734;</span>{% elif star == 0.5 %}<span class="star-icon half">&#9734;</span>{% elif star == 0 %}<span class="star-icon">&#9734;</span>{% endif %}{% endfor %}</span> &nbsp; | &nbsp; {{review.published_date.date}}</h3>
{% if request|is_mobile %}
  <div class="mobile">
Director: {% for person in review.director.all %} {{ person.first_name }} {{person.last_name}} {% endfor %} </br>
Runtime: {{ review.runtime }} minutes </br>
Starring:
{% for person in review.cast.all %}
{% if forloop.first %}
{% elif forloop.last %}, and
{% else %},
{% endif %}
{{ person.first_name }} {{person.last_name}}
{% endfor %}
</div>
<div class="review">
  {{review.body | safe}}
  </div>
</p>
{% else %}
<div class = "review">
  {{review.body | safe}}
  </div>
{% endif %}
  </article>
{% endblock %}

{% block sidebar %}
{% if not request|is_mobile %}
<table id = "cast"><tbody>
<tr><th>Directed by</th></tr>
    {% for person in review.director.all %}
<tr><td> <a href = "{% url 'persons' person.id %}">{{ person.first_name }} {{person.last_name}}</td></tr>
    {% endfor %}
<tr><th>Starring</th></tr>
    {% for person in review.cast.all %}    
    <tr><td> <a href = "{% url 'persons' person.id %}">{{ person.first_name }} {{person.last_name}}</td></tr>
    {% endfor %}

<tr><th>Runtime: {{ review.runtime }} minutes</th></tr>
  <tr><td>
<span class="imdbRatingPlugin" data-user="ur4256421" data-title="tt{{ review.imdb }}" data-style="p1"><a href="https://www.imdb.com/title/tt{{ review.imdb }}/?ref_=plg_rt_1"><img src="https://ia.media-imdb.com/images/G/01/imdb/plugins/rating/images/imdb_46x22.png" alt="{{ review.title }} ({{ review.release_date.year }}) on IMDb" />
</a></span><script>(function(d,s,id){var js,stags=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}js=d.createElement(s);js.id=id;js.src="https://ia.media-imdb.com/images/G/01/imdb/plugins/rating/js/rating.js";stags.parentNode.insertBefore(js,stags);})(document,"script","imdb-rating-api");</script>

</th></td>
</tbody></table>
{% endif %}
{% endblock %}

templates/reviews.html
{% extends "base.html" %}
{% load static %}
{% load user_agents %}

{% block title %}
<title>Reviews</title>
<meta name="description" content="Reviews of movies new and old"/>
<meta property="og:title" content="Reviews | The Movie Room" />
<meta property="og:url" content="https://themovieroom.co.uk/" />
<meta property="og:description" content="Latest reviews on themovieroom.co.uk" />
<meta property="og:image" content="{% if reviews.count > 0 %}{{ reviews.0.image_small.url }} {% else %} {% static 'images/favicon.ico' %} {% endif %}" /> 
{% endblock %}

{% block image %}
{% endblock %}

{% block body %}
{% if reviews.count > 0 %}
<table id="{% if request|is_mobile %}t03{% else %}t02{% endif %}">
<tr><th><h2>Latest Reviews</h2></th></tr>
{% for review in reviews %}
  <tr><td> <a href = "{% url 'films:title' review.link_title %}">{{review.title}} ({{review.release_date.year}})</a></td>
    <td>
    {% for star in review.stars  %}
    {% if star == 1 %} <span class="star-icon full">&#9734;</span>
    {% elif star == 0.5 %} <span class="star-icon half">&#9734;</span>
    {% elif star == 0 %} <span class="star-icon">&#9734;</span>
    {% endif %}
    {% endfor %}
</td>
</tr>
  {% endfor %}
</table>
{% endif %}
<!-- <footer class="more"><a href="#">Read More &raquo;</a></footer> -->
{% endblock %}